name: CI

on:
  push:
  pull_request:

  # Everyday at 0:37 UTC.
  schedule:
    - cron: "37 0 * * *"


# Cancel any running workflow if the CI gets triggered again.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


env:
  PYTHON_VERSION: "3.11"


jobs:
  audit:
    uses: rednafi/reflections/.github/workflows/audit.yml@master

  build:
    needs: ["audit"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: cp311
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - run: |
          echo "Cache hit: ${{ steps.cp311.outputs.cache-hit }}"

      - name: Install the dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check linter
        run: |
          echo "Checking linter conformity..."
          make lint-check

      - name: Run test
        run: |
          
      # Don't publish when the action is triggered in a pull request.
      - name: Publish the site
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          make github
